// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.project.canvas.client.resources;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
public interface MainStyles extends CssResource {
  
  String canvasContainer();
  
  String monospace();
  
  String textBoxCreateModeCanvasStyle();
  
  String textEdit();
  
  String textEditEditBox();
  
  String textEditLabelBox();
  
  String toolbox();
  
  String toolboxCommonIconStyle();
  
  String toolboxCommonSelectedIconStyle();
  
  String toolboxHeader();
  
  String toolboxTextIconStyle();
  
  String toolboxTools();
  
  String worksheet();
  
  String worksheetHeader();
  
  String worksheetPanel();
}

