// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.project.canvas.client.resources;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
public interface MainStyles extends CssResource {
  
  String canvasContainer();
  
  String toolbox();
  
  String toolboxHeader();
  
  String worksheet();
  
  String worksheetHeader();
}

