// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.project.canvas.client.resources;
import com.google.gwt.resources.client.CssResource;
public interface MainStyles extends CssResource {
  
  String canvasContainer();
  
  String cursorCreateModeCanvasStyle();
  
  String monospace();
  
  String taskListCreateModeCanvasStyle();
  
  String textBoxCreateModeCanvasStyle();
  
  String textEdit();
  
  String textEditFocused();
  String textEditNotFocused();
  String textEditNoToolbars();
  String textEditToolbar();
  
  String toolbox();
  
  String toolboxCommonIconStyle();
  
  String toolboxCommonSelectedIconStyle();
  
  String toolboxCursorIconStyle();
  
  String toolboxHeader();
  
  String toolboxTaskListIconStyle();
  
  String toolboxTextIconStyle();
  
  String toolboxTools();
  
  String worksheet();
  
  String worksheetHeader();
  String worksheetButtons();
  String worksheetOptions();
  String worksheetBackground();
  String worksheetRightButton();
  
  String worksheetPanel();
  
  String taskList();
  
  String taskListRemoveImage();
	
  String taskListTextChecked();
  
  String taskListBody();
  
  String taskListHeader();
  
  String taskListFooter();
  
  String hoverTextBoxView();
  
  String hoverTextBoxEdit();
  
  String taskImageContainer();
  
  String taskImageChecked();
  
  String taskImage();

  String imageBox();
 
  String displayNone();

  String worksheetFullView();
  
  String toolboxImageIconStyle();
  
  String imageCreateModeCanvasStyle();

  String imageToolEmpty();

  String imageToolSet();
  
  String floatingToolStyle();
  
  String toolFramePanel();
  
  String toolFrameBodyPanel();
  
  String toolFrameCloseLink(); 
  
  String toolFrameHeader(); 
  
  String toolFrameButtonsPanel(); 
  
  String toolFrameBottomRightResize();
  
  String toolFrameButton();

  String outOfBounds();
  
  String toolFrameFrontLink();
  
  String toolFrameBackLink();
  
  String worksheetDragPanel();

  String hover();
  String drag();

  String imagePickerResultImage();

  String selected();

  String textEditBox();
}